image:
  repository: ghost
  tag: "5.87.2-alpine"
  pullPolicy: IfNotPresent

domain: www.balkandevops.com

database:
  client: sqlite3

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

persistence:
  size: 5Gi
  storageClass: default

tls:
  issuer: letsencrypt-staging
