apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: platform-apps-app-of-apps
    role: child
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://github.com/balkandevops/apps
    targetRevision: HEAD
    path: platform-apps/services/ghost
    helm:
      releaseName: ghost
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ghost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
