apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: platform-infra-app-of-apps
    role: child
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: "40.0.0-ea.1"
      helm:
        valueFiles:
          - $values/platform-infra/services/traefik/values.yaml
    - repoURL: https://github.com/balkandevops/apps
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
