---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: postgres-superuser
    template:
      type: kubernetes.io/basic-auth
      data:
        username: postgres
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: postgres-superuser-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-ghost-app
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: postgres-ghost-app
    template:
      type: kubernetes.io/basic-auth
      data:
        username: ghost
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: ghost-db-password
