image:
  repository: ghcr.io/balkandevops/blog
  tag: "04ea8c46cb2471745c05edd8a47fc6c39205658c"
  pullPolicy: Always

domain: www.balkandevops.com

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

tls:
  issuer: letsencrypt-prod
