image:
  repository: ghcr.io/balkandevops/blog
  tag: "fa0a3375b519ee48a9836bfb94d2afeac53b302a"
  pullPolicy: Always

domain: www.balkandevops.com

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

tls:
  issuer: letsencrypt-prod
