image:
  repository: ghcr.io/balkandevops/blog
  tag: "dc572bc758999133f98d4a2953c29bb8d4102cb6"
  pullPolicy: Always

domain: www.balkandevops.com

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

tls:
  issuer: letsencrypt-prod
